# Generated by Django 4.1.5 on 2023-01-30 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=24, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=24, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=24, null=True, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_name', models.CharField(max_length=32, unique=True, verbose_name='Название специальности')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
            },
        ),
        migrations.CreateModel(
            name='Swearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=32, unique=True, verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Мат',
                'verbose_name_plural': 'Маты',
            },
        ),
        migrations.CreateModel(
            name='SwearingException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=32, unique=True, verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Исключение',
                'verbose_name_plural': 'Исключения',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_date_time', models.DateTimeField(auto_now=True, verbose_name='Время публикации')),
                ('original_text', models.TextField(max_length=1000, verbose_name='Оригинальный текст')),
                ('edit_text', models.TextField(max_length=1000, verbose_name='Отредактированный текст')),
                ('ip_address', models.GenericIPAddressField(verbose_name='ip-адрес пользователя')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_moderation.doctor', verbose_name='ФИО врача')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='specializations',
            field=models.ManyToManyField(to='feedback_moderation.specialization', verbose_name='Специальности'),
        ),
    ]
