# Generated by Django 4.1.5 on 2023-02-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='edit_text',
            field=models.CharField(max_length=1000, verbose_name='Отредактированный текст'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP-адрес пользователя'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='original_text',
            field=models.CharField(max_length=1000, verbose_name='Оригинальный текст'),
        ),
    ]
